services:
  app:
    container_name: nutfes-bingo-dev
    image: nutfes-bingo-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
      SUPABASE_INTERNAL_URL: http://supabase_kong_nutfes-bingo:8000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    restart: unless-stopped
    networks:
      - default
      - supabase_network_nutfes-bingo

volumes:
  node_modules:
  next_cache:

networks:
  supabase_network_nutfes-bingo:
    external: true
