version: "3"
services:
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflare"
    volumes: ["./cloudflare/prod:/home/nonroot/.cloudflared"]
    command: tunnel run

  api: # hasura
    build:
      context: .
      dockerfile: .docker/api.Dockerfile
    container_name: "bingo_api"
    volumes: [./api:/tmp/hasura-project]
    env_file:
      - ./settings/bingo-prod.env

  view-user:
    build:
      context: .
      dockerfile: .docker/view-user.Dockerfile
    container_name: "view-user"
    volumes: [./view-user:/app]
    command: sh -c "npm install && npm run build && npm run start"
    env_file:
      - ./settings/bingo-prod.env

  view-admin:
    build:
      context: .
      dockerfile: .docker/view-admin.Dockerfile
    container_name: "view-admin"
    volumes:
      - ./view-admin:/app
    command: sh -c "npm install && npm run build && npm run start"
    env_file:
      - ./settings/admin-prod.env
