services:
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflare"
    command: tunnel --no-autoupdate run --token eyJhIjoiMzBhYmFkZjQ2NmYyOGU1NDc5Y2RhNjRlN2JiNWM5YWUiLCJ0IjoiNTE1YTk0YWYtODhmZC00MGQ0LWJiNzgtOWM3YTk0YjA2OTZiIiwicyI6InJud2wzeUxnUVp4akZIK2FwZXlQclNlRWt1bmdjNFJBbGlTd3hlN0FrcHM9In0=
    restart: unless-stopped
    depends_on:
      - view-user
      - view-admin
    networks:
      - bingo-network
      - supabase_default

  view-user:
    image: node:25-alpine
    container_name: "view-user"
    volumes:
      - ./view-user:/app
      - ./shared:/shared
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "10000:3000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - bingo-network
      - supabase_default

  view-admin:
    image: node:25-alpine
    container_name: "view-admin"
    volumes:
      - ./view-admin:/app
      - ./shared:/shared
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "10001:3000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - bingo-network
      - supabase_default

networks:
  bingo-network:
    external: true
  supabase_default:
    external: true

