services:
  view-user:
    image: node:25-alpine
    container_name: "view-user"
    volumes:
      - ./view-user:/app
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "10000:3000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true

  view-admin:
    image: node:25-alpine
    container_name: "view-admin"
    volumes:
      - ./view-admin:/app
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "10001:3000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true

networks:
  default:
    name: bingo-network
    external: true
