services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "bingo-web"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: pnpm dev
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true

networks:
  default:
    name: bingo-network
    external: true

volumes:
  node_modules:
