version: '3.9'
services:
  user-front:
    build: ./
    container_name: "view-user"
    volumes:
      - ./view-user:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
