package main

import (
	"api/infrastructure/datastore"
	"api/infrastructure/routing"
	"api/interface/controller"
	"api/usecase"
	_ "api/docs" // docs is generated by Swag CLI
)

// @title go_learn API
// @version 1.0
// @description go_learn API
// @host localhost:1323
// @BasePath /
// @schemes http
func main() {
	// データベース接続を初期化
	db := datastore.NewDB()

	// 依存関係を注入 (DI)
	numberRepository := datastore.NewNumberRepository(db)
	numberUsecase := usecase.NewNumberUsecase(numberRepository)
	numberController := controller.NewNumberController(numberUsecase)

	// ルーティングを初期化
	e := routing.NewRouter(numberController)

	// ポートを開く、docker-compose.ymlと同じポート番号にする
	e.Logger.Fatal(e.Start(":1323"))
}
