tunnel: 515a94af-88fd-40d4-bb78-9c7a94b0696b
credentials-file: /home/nonroot/.cloudflared/515a94af-88fd-40d4-bb78-9c7a94b0696b.json
protocol: http2

ingress:
  - hostname: bingo.nutfes.net
    service: http://view-user:3000
  - hostname: bingo-admin.nutfes.net
    service: http://view-admin:3000
  - hostname: bingo-api.nutfes.net
    service: http://api:8080
  - service: http_status:404
