# アンケート配信状態の取得(Get)
query GetLatestEventSurvey {
  events(orderBy: { id: DESC }, limit: 1) {
    id
    surveyUrl
    isSurveyActive
  }
}

# アンケート配信レコードの追加(Create)
mutation CreateEventSurvey($surveyUrl: String!, $isSurveyActive: Boolean!) {
  insertEventsOne(
    object: { surveyUrl: $surveyUrl, isSurveyActive: $isSurveyActive }
  ) {
    id
    surveyUrl
    isSurveyActive
  }
}
