begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.numbers (
  id bigint generated by default as identity primary key,
  number integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint numbers_number_range check (number between 1 and 99),
  constraint numbers_number_unique unique (number)
);

create table if not exists public.prizes (
  id bigint generated by default as identity primary key,
  name_jp text not null default '',
  name_en text,
  is_won boolean not null default false,
  image_path text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_state (
  id integer primary key default 1 check (id = 1),
  survey_url text not null default '',
  is_survey_active boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reach_logs (
  id bigint generated by default as identity primary key,
  delta integer not null check (delta in (-1, 0, 1)),
  reach_num integer not null check (reach_num >= 0),
  source text not null default 'public' check (source in ('public', 'admin', 'system')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.stamp_triggers (
  id bigint generated by default as identity primary key,
  name text not null check (name in ('angry', 'cracker', 'crap', 'good', 'heart', 'peace', 'sad', 'skull', 'smile', 'surprise')),
  created_at timestamptz not null default timezone('utc', now())
);

insert into public.app_state (id, survey_url, is_survey_active)
values (1, '', false)
on conflict (id) do nothing;

create index if not exists reach_logs_created_at_desc_idx on public.reach_logs (created_at desc);
create index if not exists stamp_triggers_created_at_desc_idx on public.stamp_triggers (created_at desc);
create index if not exists prizes_is_won_idx on public.prizes (is_won);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin(target_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = coalesce(target_user, auth.uid())
      and role = 'admin'
  );
$$;

create or replace function public.record_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := current_num + 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'public');

  return new_num;
end;
$$;

create or replace function public.increment_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := current_num + 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'admin');

  return new_num;
end;
$$;

create or replace function public.decrement_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := greatest(current_num - 1, 0);

  insert into public.reach_logs (delta, reach_num, source)
  values (-1, new_num, 'admin');

  return new_num;
end;
$$;

grant execute on function public.record_reach() to anon, authenticated;
grant execute on function public.increment_reach() to authenticated;
grant execute on function public.decrement_reach() to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;

create or replace trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace trigger numbers_set_updated_at
before update on public.numbers
for each row execute function public.set_updated_at();

create or replace trigger prizes_set_updated_at
before update on public.prizes
for each row execute function public.set_updated_at();

create or replace trigger app_state_set_updated_at
before update on public.app_state
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.numbers enable row level security;
alter table public.prizes enable row level security;
alter table public.app_state enable row level security;
alter table public.reach_logs enable row level security;
alter table public.stamp_triggers enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "numbers_read_all" on public.numbers;
create policy "numbers_read_all"
on public.numbers
for select
to anon, authenticated
using (true);

drop policy if exists "numbers_admin_insert" on public.numbers;
create policy "numbers_admin_insert"
on public.numbers
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "numbers_admin_update" on public.numbers;
create policy "numbers_admin_update"
on public.numbers
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "numbers_admin_delete" on public.numbers;
create policy "numbers_admin_delete"
on public.numbers
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "prizes_read_all" on public.prizes;
create policy "prizes_read_all"
on public.prizes
for select
to anon, authenticated
using (true);

drop policy if exists "prizes_admin_insert" on public.prizes;
create policy "prizes_admin_insert"
on public.prizes
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "prizes_admin_update" on public.prizes;
create policy "prizes_admin_update"
on public.prizes
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "prizes_admin_delete" on public.prizes;
create policy "prizes_admin_delete"
on public.prizes
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "app_state_read_all" on public.app_state;
create policy "app_state_read_all"
on public.app_state
for select
to anon, authenticated
using (true);

drop policy if exists "app_state_admin_update" on public.app_state;
create policy "app_state_admin_update"
on public.app_state
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "reach_logs_read_all" on public.reach_logs;
create policy "reach_logs_read_all"
on public.reach_logs
for select
to anon, authenticated
using (true);

drop policy if exists "stamp_triggers_read_all" on public.stamp_triggers;
create policy "stamp_triggers_read_all"
on public.stamp_triggers
for select
to anon, authenticated
using (true);

drop policy if exists "stamp_triggers_insert_all" on public.stamp_triggers;
create policy "stamp_triggers_insert_all"
on public.stamp_triggers
for insert
to anon, authenticated
with check (name is not null);

insert into storage.buckets (id, name, public)
values ('prize-images', 'prize-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "prize_images_public_read" on storage.objects;
create policy "prize_images_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'prize-images');

drop policy if exists "prize_images_admin_insert" on storage.objects;
create policy "prize_images_admin_insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'prize-images' and (select public.is_admin()));

drop policy if exists "prize_images_admin_update" on storage.objects;
create policy "prize_images_admin_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'prize-images' and (select public.is_admin()))
with check (bucket_id = 'prize-images' and (select public.is_admin()));

drop policy if exists "prize_images_admin_delete" on storage.objects;
create policy "prize_images_admin_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'prize-images' and (select public.is_admin()));

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'numbers'
  ) then
    alter publication supabase_realtime add table public.numbers;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'prizes'
  ) then
    alter publication supabase_realtime add table public.prizes;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'app_state'
  ) then
    alter publication supabase_realtime add table public.app_state;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reach_logs'
  ) then
    alter publication supabase_realtime add table public.reach_logs;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'stamp_triggers'
  ) then
    alter publication supabase_realtime add table public.stamp_triggers;
  end if;
end
$$;

commit;
