-- Baseline schema for fresh annual production databases.
-- Squashed from the 2026 migration history after removing unused Realtime/Supavisor/Analytics initialization.
-- This project treats production data as event-scoped; do not apply this squash to a database that still expects the old migration history.

-- BEGIN squashed: 20260313000000_initial_schema.sql
begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.numbers (
  id bigint generated by default as identity primary key,
  number integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint numbers_number_range check (number between 1 and 99),
  constraint numbers_number_unique unique (number)
);

create table if not exists public.prizes (
  id bigint generated by default as identity primary key,
  name_jp text not null default '',
  name_en text,
  is_won boolean not null default false,
  image_path text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_state (
  id integer primary key default 1 check (id = 1),
  survey_url text not null default '',
  is_survey_active boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reach_logs (
  id bigint generated by default as identity primary key,
  delta integer not null check (delta in (-1, 0, 1)),
  reach_num integer not null check (reach_num >= 0),
  source text not null default 'public' check (source in ('public', 'admin', 'system')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.stamp_triggers (
  id bigint generated by default as identity primary key,
  name text not null check (name in ('angry', 'cracker', 'crap', 'good', 'heart', 'peace', 'sad', 'skull', 'smile', 'surprise')),
  created_at timestamptz not null default timezone('utc', now())
);

insert into public.app_state (id, survey_url, is_survey_active)
values (1, '', false)
on conflict (id) do nothing;

create index if not exists reach_logs_created_at_desc_idx on public.reach_logs (created_at desc);
create index if not exists stamp_triggers_created_at_desc_idx on public.stamp_triggers (created_at desc);
create index if not exists prizes_is_won_idx on public.prizes (is_won);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin(target_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = coalesce(target_user, auth.uid())
      and role = 'admin'
  );
$$;

create or replace function public.record_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := current_num + 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'public');

  return new_num;
end;
$$;

create or replace function public.increment_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := current_num + 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'admin');

  return new_num;
end;
$$;

create or replace function public.decrement_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  select coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
  into current_num;

  new_num := greatest(current_num - 1, 0);

  insert into public.reach_logs (delta, reach_num, source)
  values (-1, new_num, 'admin');

  return new_num;
end;
$$;

revoke execute on function public.record_reach() from public, anon, authenticated;
grant execute on function public.increment_reach() to authenticated;
grant execute on function public.decrement_reach() to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;

create or replace trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace trigger numbers_set_updated_at
before update on public.numbers
for each row execute function public.set_updated_at();

create or replace trigger prizes_set_updated_at
before update on public.prizes
for each row execute function public.set_updated_at();

create or replace trigger app_state_set_updated_at
before update on public.app_state
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.numbers enable row level security;
alter table public.prizes enable row level security;
alter table public.app_state enable row level security;
alter table public.reach_logs enable row level security;
alter table public.stamp_triggers enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "numbers_read_all" on public.numbers;
create policy "numbers_read_all"
on public.numbers
for select
to anon, authenticated
using (true);

drop policy if exists "numbers_admin_insert" on public.numbers;
create policy "numbers_admin_insert"
on public.numbers
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "numbers_admin_update" on public.numbers;
create policy "numbers_admin_update"
on public.numbers
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "numbers_admin_delete" on public.numbers;
create policy "numbers_admin_delete"
on public.numbers
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "prizes_read_all" on public.prizes;
create policy "prizes_read_all"
on public.prizes
for select
to anon, authenticated
using (true);

drop policy if exists "prizes_admin_insert" on public.prizes;
create policy "prizes_admin_insert"
on public.prizes
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "prizes_admin_update" on public.prizes;
create policy "prizes_admin_update"
on public.prizes
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "prizes_admin_delete" on public.prizes;
create policy "prizes_admin_delete"
on public.prizes
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "app_state_read_all" on public.app_state;
create policy "app_state_read_all"
on public.app_state
for select
to anon, authenticated
using (true);

drop policy if exists "app_state_admin_update" on public.app_state;
create policy "app_state_admin_update"
on public.app_state
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "reach_logs_read_all" on public.reach_logs;
create policy "reach_logs_read_all"
on public.reach_logs
for select
to anon, authenticated
using (true);

drop policy if exists "stamp_triggers_read_all" on public.stamp_triggers;
create policy "stamp_triggers_read_all"
on public.stamp_triggers
for select
to anon, authenticated
using (true);

drop policy if exists "stamp_triggers_insert_all" on public.stamp_triggers;

insert into storage.buckets (id, name, public)
values ('prize-images', 'prize-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "prize_images_public_read" on storage.objects;
create policy "prize_images_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'prize-images');

drop policy if exists "prize_images_admin_insert" on storage.objects;
create policy "prize_images_admin_insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'prize-images' and (select public.is_admin()));

drop policy if exists "prize_images_admin_update" on storage.objects;
create policy "prize_images_admin_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'prize-images' and (select public.is_admin()))
with check (bucket_id = 'prize-images' and (select public.is_admin()));

drop policy if exists "prize_images_admin_delete" on storage.objects;
create policy "prize_images_admin_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'prize-images' and (select public.is_admin()));

commit;

-- END squashed: 20260313000000_initial_schema.sql

-- BEGIN squashed: 20260521000000_public_operation_hardening.sql
begin;

alter table public.app_state
add column if not exists reach_count integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'app_state_reach_count_nonnegative'
      and conrelid = 'public.app_state'::regclass
  ) then
    alter table public.app_state
    add constraint app_state_reach_count_nonnegative check (reach_count >= 0);
  end if;
end
$$;

update public.app_state
set reach_count = greatest(
  reach_count,
  coalesce((
    select reach_num
    from public.reach_logs
    order by created_at desc, id desc
    limit 1
  ), 0)
)
where id = 1;

create table if not exists public.public_action_limits (
  action text not null check (action in ('reaction_stamp')),
  client_hash text not null check (char_length(client_hash) between 32 and 128),
  last_sent_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (action, client_hash)
);

create table if not exists public.reach_submissions (
  client_hash text primary key check (char_length(client_hash) between 32 and 128),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists public_action_limits_updated_at_idx
on public.public_action_limits (updated_at desc);

create index if not exists reach_submissions_created_at_idx
on public.reach_submissions (created_at desc);

alter table public.public_action_limits enable row level security;
alter table public.reach_submissions enable row level security;

drop policy if exists "stamp_triggers_insert_all" on public.stamp_triggers;

drop function if exists public.record_reach();

create or replace function public.claim_public_action(
  p_action text,
  p_client_hash text,
  p_min_interval interval
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed boolean;
begin
  if p_client_hash is null or char_length(p_client_hash) < 32 or char_length(p_client_hash) > 128 then
    raise exception 'invalid_public_client' using errcode = '22023';
  end if;

  insert into public.public_action_limits as current_limit (
    action,
    client_hash,
    last_sent_at,
    updated_at
  )
  values (
    p_action,
    p_client_hash,
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (action, client_hash) do update
    set last_sent_at = excluded.last_sent_at,
        updated_at = excluded.updated_at
    where current_limit.last_sent_at <= timezone('utc', now()) - p_min_interval
  returning true into claimed;

  if not coalesce(claimed, false) then
    raise exception 'public_action_rate_limited' using errcode = 'P0001';
  end if;
end;
$$;

create or replace function public.record_reaction_stamp(
  stamp_name text,
  client_hash text
)
returns public.stamp_triggers
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_stamp public.stamp_triggers%rowtype;
begin
  perform public.claim_public_action('reaction_stamp', client_hash, interval '2 seconds');

  insert into public.stamp_triggers (name)
  values (stamp_name)
  returning * into inserted_stamp;

  return inserted_stamp;
end;
$$;

create or replace function public.record_reach(client_hash text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  accepted_client_hash text;
  new_num integer;
begin
  if client_hash is null or char_length(client_hash) < 32 or char_length(client_hash) > 128 then
    raise exception 'invalid_public_client' using errcode = '22023';
  end if;

  insert into public.reach_submissions (client_hash)
  values (client_hash)
  on conflict (client_hash) do nothing
  returning client_hash into accepted_client_hash;

  if accepted_client_hash is null then
    select reach_count
    into new_num
    from public.app_state
    where id = 1;

    return coalesce(new_num, 0);
  end if;

  update public.app_state
  set reach_count = reach_count + 1
  where id = 1
  returning reach_count into new_num;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'public');

  return new_num;
end;
$$;

create or replace function public.increment_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  update public.app_state
  set reach_count = reach_count + 1
  where id = 1
  returning reach_count into new_num;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'admin');

  return new_num;
end;
$$;

create or replace function public.decrement_reach()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if not public.is_admin() then
    raise exception 'admin role is required' using errcode = '42501';
  end if;

  select reach_count
  into current_num
  from public.app_state
  where id = 1
  for update;

  new_num := greatest(coalesce(current_num, 0) - 1, 0);

  update public.app_state
  set reach_count = new_num
  where id = 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (
    case when new_num < coalesce(current_num, 0) then -1 else 0 end,
    new_num,
    'admin'
  );

  return new_num;
end;
$$;

revoke execute on function public.claim_public_action(text, text, interval) from public, anon, authenticated;
revoke execute on function public.record_reaction_stamp(text, text) from public, anon, authenticated;
revoke execute on function public.record_reach(text) from public, anon, authenticated;

grant execute on function public.claim_public_action(text, text, interval) to service_role;
grant execute on function public.record_reaction_stamp(text, text) to service_role;
grant execute on function public.record_reach(text) to service_role;
grant execute on function public.increment_reach() to authenticated;
grant execute on function public.decrement_reach() to authenticated;

commit;

-- END squashed: 20260521000000_public_operation_hardening.sql

-- BEGIN squashed: 20260525000000_lock_down_public_api_surface.sql
begin;

revoke usage on schema public from public, anon, authenticated;
revoke all privileges on all tables in schema public from public, anon, authenticated;
revoke all privileges on all sequences in schema public from public, anon, authenticated;

alter default privileges in schema public revoke all on tables from public, anon, authenticated;
alter default privileges in schema public revoke all on sequences from public, anon, authenticated;
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "numbers_read_all" on public.numbers;
drop policy if exists "numbers_admin_insert" on public.numbers;
drop policy if exists "numbers_admin_update" on public.numbers;
drop policy if exists "numbers_admin_delete" on public.numbers;
drop policy if exists "prizes_read_all" on public.prizes;
drop policy if exists "prizes_admin_insert" on public.prizes;
drop policy if exists "prizes_admin_update" on public.prizes;
drop policy if exists "prizes_admin_delete" on public.prizes;
drop policy if exists "app_state_read_all" on public.app_state;
drop policy if exists "app_state_admin_update" on public.app_state;
drop policy if exists "reach_logs_read_all" on public.reach_logs;
drop policy if exists "stamp_triggers_read_all" on public.stamp_triggers;
drop policy if exists "stamp_triggers_insert_all" on public.stamp_triggers;

drop policy if exists "profiles_service_role_all" on public.profiles;
create policy "profiles_service_role_all"
on public.profiles
for all
to service_role
using (true)
with check (true);

drop policy if exists "numbers_service_role_all" on public.numbers;
create policy "numbers_service_role_all"
on public.numbers
for all
to service_role
using (true)
with check (true);

drop policy if exists "prizes_service_role_all" on public.prizes;
create policy "prizes_service_role_all"
on public.prizes
for all
to service_role
using (true)
with check (true);

drop policy if exists "app_state_service_role_all" on public.app_state;
create policy "app_state_service_role_all"
on public.app_state
for all
to service_role
using (true)
with check (true);

drop policy if exists "reach_logs_service_role_all" on public.reach_logs;
create policy "reach_logs_service_role_all"
on public.reach_logs
for all
to service_role
using (true)
with check (true);

drop policy if exists "stamp_triggers_service_role_all" on public.stamp_triggers;
create policy "stamp_triggers_service_role_all"
on public.stamp_triggers
for all
to service_role
using (true)
with check (true);

drop policy if exists "public_action_limits_service_role_all" on public.public_action_limits;
create policy "public_action_limits_service_role_all"
on public.public_action_limits
for all
to service_role
using (true)
with check (true);

drop policy if exists "reach_submissions_service_role_all" on public.reach_submissions;
create policy "reach_submissions_service_role_all"
on public.reach_submissions
for all
to service_role
using (true)
with check (true);

drop policy if exists "prize_images_public_read" on storage.objects;
drop policy if exists "prize_images_admin_insert" on storage.objects;
drop policy if exists "prize_images_admin_update" on storage.objects;
drop policy if exists "prize_images_admin_delete" on storage.objects;

drop policy if exists "prize_images_service_role_all" on storage.objects;
create policy "prize_images_service_role_all"
on storage.objects
for all
to service_role
using (bucket_id = 'prize-images')
with check (bucket_id = 'prize-images');

drop function if exists public.record_reach();

create or replace function public.claim_public_action(
  p_action text,
  p_client_hash text,
  p_min_interval interval
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  claimed boolean;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role is required' using errcode = '42501';
  end if;

  if p_client_hash is null or char_length(p_client_hash) < 32 or char_length(p_client_hash) > 128 then
    raise exception 'invalid_public_client' using errcode = '22023';
  end if;

  insert into public.public_action_limits as current_limit (
    action,
    client_hash,
    last_sent_at,
    updated_at
  )
  values (
    p_action,
    p_client_hash,
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (action, client_hash) do update
    set last_sent_at = excluded.last_sent_at,
        updated_at = excluded.updated_at
    where current_limit.last_sent_at <= timezone('utc', now()) - p_min_interval
  returning true into claimed;

  if not coalesce(claimed, false) then
    raise exception 'public_action_rate_limited' using errcode = 'P0001';
  end if;
end;
$$;

create or replace function public.record_reaction_stamp(
  stamp_name text,
  client_hash text
)
returns public.stamp_triggers
language plpgsql
security invoker
set search_path = public
as $$
declare
  inserted_stamp public.stamp_triggers%rowtype;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role is required' using errcode = '42501';
  end if;

  perform public.claim_public_action('reaction_stamp', client_hash, interval '2 seconds');

  insert into public.stamp_triggers (name)
  values (stamp_name)
  returning * into inserted_stamp;

  return inserted_stamp;
end;
$$;

create or replace function public.record_reach(client_hash text)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  accepted_client_hash text;
  new_num integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role is required' using errcode = '42501';
  end if;

  if client_hash is null or char_length(client_hash) < 32 or char_length(client_hash) > 128 then
    raise exception 'invalid_public_client' using errcode = '22023';
  end if;

  insert into public.reach_submissions (client_hash)
  values (client_hash)
  on conflict (client_hash) do nothing
  returning client_hash into accepted_client_hash;

  if accepted_client_hash is null then
    select reach_count
    into new_num
    from public.app_state
    where id = 1;

    return coalesce(new_num, 0);
  end if;

  update public.app_state
  set reach_count = reach_count + 1
  where id = 1
  returning reach_count into new_num;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'public');

  return new_num;
end;
$$;

create or replace function public.increment_reach()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_num integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role is required' using errcode = '42501';
  end if;

  update public.app_state
  set reach_count = reach_count + 1
  where id = 1
  returning reach_count into new_num;

  insert into public.reach_logs (delta, reach_num, source)
  values (1, new_num, 'admin');

  return new_num;
end;
$$;

create or replace function public.decrement_reach()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_num integer;
  new_num integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role is required' using errcode = '42501';
  end if;

  select reach_count
  into current_num
  from public.app_state
  where id = 1
  for update;

  new_num := greatest(coalesce(current_num, 0) - 1, 0);

  update public.app_state
  set reach_count = new_num
  where id = 1;

  insert into public.reach_logs (delta, reach_num, source)
  values (
    case when new_num < coalesce(current_num, 0) then -1 else 0 end,
    new_num,
    'admin'
  );

  return new_num;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

revoke execute on all functions in schema public from public, anon, authenticated;

grant execute on function public.claim_public_action(text, text, interval) to service_role;
grant execute on function public.record_reaction_stamp(text, text) to service_role;
grant execute on function public.record_reach(text) to service_role;
grant execute on function public.increment_reach() to service_role;
grant execute on function public.decrement_reach() to service_role;
grant execute on function public.is_admin(uuid) to service_role;
grant execute on function public.set_updated_at() to service_role;

do $$
begin
  if exists (
    select 1
    from pg_roles
    where rolname = 'supabase_auth_admin'
  ) then
    execute 'grant execute on function public.handle_new_user() to supabase_auth_admin';
    execute 'grant execute on function public.set_updated_at() to supabase_auth_admin';
  end if;
end
$$;


commit;

-- END squashed: 20260525000000_lock_down_public_api_surface.sql

-- BEGIN squashed: 20260618000000_admin_bootstrap_private_functions.sql
begin;

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;
revoke all on schema private from service_role;

create or replace function private.bootstrap_initial_admin(
  p_user_id uuid,
  p_email text
)
returns table (
  user_id uuid,
  email text,
  role text,
  was_admin boolean
)
language plpgsql
security definer
set search_path = public, auth, private
as $$
declare
  normalized_email text := lower(nullif(btrim(p_email), ''));
  other_admin_count integer;
  was_admin_before boolean;
begin
  if p_user_id is null then
    raise exception 'user_id is required' using errcode = '22023';
  end if;

  if normalized_email is null then
    raise exception 'email is required' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from auth.users
    where id = p_user_id
      and lower(email) = normalized_email
  ) then
    raise exception 'auth user does not match id/email' using errcode = 'P0001';
  end if;

  select count(*)
  into other_admin_count
  from public.profiles
  where role = 'admin'
    and id <> p_user_id;

  if other_admin_count > 0 then
    raise exception 'initial admin already exists' using errcode = 'P0001';
  end if;

  select exists (
    select 1
    from public.profiles
    where id = p_user_id
      and role = 'admin'
  )
  into was_admin_before;

  insert into public.profiles (id, email, role)
  values (p_user_id, normalized_email, 'admin')
  on conflict (id) do update
    set email = excluded.email,
        role = 'admin',
        updated_at = timezone('utc', now());

  return query
  select profiles.id, profiles.email, profiles.role, was_admin_before
  from public.profiles
  where profiles.id = p_user_id;
end;
$$;

comment on schema private is
  'Operational functions for LXC-only maintenance tasks. This schema is not exposed through PostgREST.';

comment on function private.bootstrap_initial_admin(uuid, text) is
  'Promotes the first production Auth user to profiles.role = admin. Intended for psql-only bootstrap operations.';

revoke all on function private.bootstrap_initial_admin(uuid, text) from public;
revoke all on function private.bootstrap_initial_admin(uuid, text) from anon;
revoke all on function private.bootstrap_initial_admin(uuid, text) from authenticated;
revoke all on function private.bootstrap_initial_admin(uuid, text) from service_role;

commit;

-- END squashed: 20260618000000_admin_bootstrap_private_functions.sql
