  on:
    pull_request:
      branches:
        - develop
      paths:
        - "view-user/**"

  jobs:
    prettier:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm
            cache-dependency-path: view-user/package-lock.json

        - run: npm install
          working-directory: view-user

        # - name: prettier format
        #   run: npm run format
        #   working-directory: view-user

        - name: lint
          run: npm run lint:fix
          working-directory: view-user

        # - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        #   with:
        #     branch: develop
        #     commit_message: formatted by workflow
        #     commit_options: '--no-verify'
