name: Automatically labeling pull request.

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-change-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
      PR_BRANCH: ${{ github.event.pull_request.head.ref }}

    steps:
      - uses: actions/checkout@v2

      # 変更されたファイルを取得
      - name: get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'view-user/**'
              - 'view-admin/**'
            backend:
              - 'api/**'
              - 'hasura/**'
            infra:
              - 'docker-compose.*'
              - '**/*Dockerfile'
            src:
              - 'src/components/common/**'
              - 'src/gql/**'
              - 'src/pages/**'
              - 'src/styles/**'
              - 'src/type/**'

      # PRにラベルを付与
      - name: Auto frontend labeling
        if: steps.changes.outputs.frontend == 'true'
        run: |
          if [[ "${{ steps.changes.outputs.frontend }}" == *"view-user/"* ]]; then
            gh pr edit ${{ env.PR_NUMBER }} --add-label "frontend-user"
          elif [[ "${{ steps.changes.outputs.frontend }}" == *"view-admin/"* ]]; then
            gh pr edit ${{ env.PR_NUMBER }} --add-label "frontend-admin"
          fi
      - name: Auto backend labeling
        if: steps.changes.outputs.backend == 'true'
        run: |
          if [[ "${{ steps.changes.outputs.backend }}" == *"hasura/"* ]]; then
            gh pr edit ${{ env.PR_NUMBER }} --add-label "backend-hasura"
          fi
      - name: Auto src component common labeling
        if: steps.changes.outputs.src == 'true' && "${{ steps.changes.outputs.src }}" == *"src/components/"*
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label "component"
      - name: Auto src gql labeling
        if: steps.changes.outputs.src == 'true' && "${{ steps.changes.outputs.src }}" == *"src/gql/"*
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label "gql"
      - name: Auto src pages labeling
        if: steps.changes.outputs.src == 'true' && "${{ steps.changes.outputs.src }}" == *"src/pages/"*
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label "pages"
      - name: Auto src styles labeling
        if: steps.changes.outputs.src == 'true' && "${{ steps.changes.outputs.src }}" == *"src/styles/"*
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label "styles"
      - name: Auto src type labeling
        if: steps.changes.outputs.src == 'true' && ("${{ steps.changes.outputs.src }}" == *"src/type/" || "${{ steps.changes.outputs.src }}" == *"src/types/" ) && "${{ steps.changes.outputs.src }}" != *"view-user/"*
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label "type"
      - name: Auto infra labeling
        if: steps.changes.outputs.infra == 'true'
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label infra
      - name: Auto labeling
        if: steps.label_name.outputs.label_name
        run: gh pr edit ${{ env.PR_NUMBER }} --add-label ${{ steps.label_name.outputs.label_name }}

      # PRにAssigneeを付与
      - name: Auto assignee
        if: toJSON(github.event.pull_request.assignees) == '[]'
        run: gh pr edit ${{ env.PR_NUMBER }} --add-assignee ${{ env.PR_ASSIGNEE }}
