on:
  pull_request:
    branches:
      - develop
    paths:
      - "view-admin/**"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.3.1
          cache: npm
          cache-dependency-path: view-admin/package-lock.json

      - run: npm install
        working-directory: view-admin

      - name: lint
        run: npm run lint:fix
        working-directory: view-admin

  lint_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.3.1]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: view-admin/package-lock.json
      - name: Install Dependencies
        run: npm ci
        working-directory: view-admin

      - name: Run ESLint Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "src/**/*.{ts,tsx}"
          workdir: view-admin
